# -*- coding: utf-8 -*-
"""Salinan dari Google Colab Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192E-1nrEwqE_LUVRxomBPK1JLo8kLezW

# **Klasifikasi Mutu Kayu Berdasarkan Cacat Mata Kayu Menggunakan Metode Thresholding & Morfologi**

# 1. Pendahuluan & Problem Statement

## Deskripsi dataset dan tujuan analisis

## Justifikasi Pemilihan Teknik

# 2. Preprocessing Pipeline

**Teknik 1 – Image Resizing**

Image resizing digunakan untuk menyeragamkan ukuran semua citra papan kayu. Dengan membatasi ukuran (misalnya sisi terpanjang 512 piksel), proses komputasi jadi lebih ringan dan skala objek (termasuk mata kayu) lebih konsisten sehingga mudah dibandingkan dan dianalisis.

**Teknik 2 – Transformasi RGB ke Grayscale**

Transformasi RGB ke grayscale menyederhanakan citra dari 3 kanal warna menjadi 1 kanal intensitas. Ini dilakukan karena deteksi mata kayu lebih bergantung pada perbedaan terang–gelap, sehingga pengolahan jadi lebih sederhana dan fokus pada kontras antara kayu bersih dan mata kayu.

**Teknik 3 – Histogram Equalization**

Histogram equalization digunakan untuk meningkatkan kontras pada citra grayscale. Dengan teknik ini, area mata kayu yang lebih gelap menjadi lebih menonjol dibanding kayu normal, sehingga batasnya lebih jelas dan memudahkan proses segmentasi di tahap berikutnya.
"""

# Preprocessing Pipeline
#Teknik 1: [nama] + justifikasi + hasil
#dst
#Analisis perbandingan before-after

"""## Modul"""

!pip install -q opencv-python scikit-image matplotlib seaborn pandas numpy scikit-learn gdown

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2

from skimage import filters, morphology, segmentation, measure, feature

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)
from sklearn.preprocessing import StandardScaler, LabelEncoder

import os
import zipfile
import warnings
import gdown

warnings.filterwarnings('ignore')

plt.rcParams['figure.figsize'] = (6, 4)
sns.set(style="whitegrid")

from google.colab import drive
drive.mount('/content/drive')

import os


root_dir = "/content/drive/MyDrive/Tubes_PCD/"

print("Membaca isi folder dataset di:", root_dir)
print(os.listdir(root_dir))

"""# Image Resizing"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

def show_image(title, img, cmap=None):
    plt.figure()
    plt.title(title)
    if cmap is not None:
        plt.imshow(img, cmap=cmap)
    else:
        if img.ndim == 3:
            img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            plt.imshow(img_rgb)
        else:
            plt.imshow(img, cmap='gray')
    plt.axis('off')
    plt.show()

image_dir = os.path.join(root_dir, "Images - 1", "Images - 1")
image_files = sorted([
    f for f in os.listdir(image_dir)
    if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp'))
])

print("Jumlah file di folder :", len(image_files))
print("Beberapa file pertama :", image_files[:5])

idx = 0
img_path = os.path.join(image_dir, image_files[idx])
print("Memakai contoh gambar :", img_path)

img_bgr = cv2.imread(img_path)

def resize_keep_aspect(img, max_dim=512):
    h, w = img.shape[:2]
    scale = max_dim / max(h, w)
    new_w = int(w * scale)
    new_h = int(h * scale)
    return cv2.resize(img, (new_w, new_h), interpolation=cv2.INTER_AREA)

img_resized = resize_keep_aspect(img_bgr, max_dim=512)

print("Shape asli   :", img_bgr.shape)
print("Shape resize :", img_resized.shape)

fig, axes = plt.subplots(1, 2, figsize=(8, 4))
fig.suptitle("Teknik 1 - Image Resizing (1 Gambar Contoh)", fontsize=12, fontweight='bold')

axes[0].imshow(cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB))
axes[0].set_title("RGB Asli")
axes[0].axis('off')

axes[1].imshow(cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB))
axes[1].set_title("RGB Resized")
axes[1].axis('off')

plt.tight_layout()
plt.show()

"""##  Transformasi RGB (Grayscale)"""

img_gray = cv2.cvtColor(img_resized, cv2.COLOR_BGR2GRAY)

print("Shape grayscale:", img_gray.shape)

fig, axes = plt.subplots(1, 2, figsize=(8, 4))
fig.suptitle("Teknik 2 - RGB -> Grayscale (1 Gambar Contoh)",
             fontsize=12, fontweight='bold')

axes[0].imshow(cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB))
axes[0].set_title("RGB Resized")
axes[0].axis('off')

axes[1].imshow(img_gray, cmap='gray')
axes[1].set_title("Grayscale")
axes[1].axis('off')

plt.tight_layout()
plt.show()

"""## Histogram Equelization"""

img_eq = cv2.equalizeHist(img_gray)

print("Shape setelah HE:", img_eq.shape)

fig, axes = plt.subplots(1, 2, figsize=(8, 4))
fig.suptitle("Teknik 3 - Grayscale vs HE (1 Gambar Contoh)",
             fontsize=12, fontweight='bold')

axes[0].imshow(img_gray, cmap='gray')
axes[0].set_title("Grayscale (Before HE)")
axes[0].axis('off')

axes[1].imshow(img_eq, cmap='gray')
axes[1].set_title("Grayscale + HE")
axes[1].axis('off')

plt.tight_layout()
plt.show()

"""# 3. Image Processing & Transformation

**Teknik 1 - Gaussian Blur**

Teknik gaussian blur digunakan untuk mengurangi noise yang terdapat pada citra. Dalam konteks ini, gaussian blur dipakai untuk menghilangkan noise serat kayu halus yang dapat dianggap sebagai mata kayu kecil.

**Teknik 2 - Thresholding**

Thresholding merupakan salah satu teknik umum yang digunakan dalam segmentasi citra untuk memisahkan objek dari latar belakang dengan menggunakan nilai ambang tertentu. Pada proyek ini, thresholding digunakan untuk memisahkan mata kayu dari latar belakang berdasarkan intensitas warna yang telah diberi kontras pada operasi sebelumnya.

**Teknik 3 - Operasi Morfologi (opening)**

Operasi morfologi pembukaan (opening) digunakan untuk menghaluskan permukaan, dalam konteks ini, opening dipakai untuk membersihkan titik-titik putih kecil yang bukan mata kayu berdasarkan hasil operasi thresholding sebelumnya.
"""

# Image Processing & Transformation
# Teknik 1: [nama] + parameter + hasil
# dst
# Analisis efektivitas setiap teknik

"""##  **Teknik 1 - Gaussian Blur**"""

img_blur = cv2.GaussianBlur(img_eq, (5,5), 0)

fig, axes = plt.subplots(1, 2, figsize=(8, 4))
fig.suptitle("Teknik 4 - Gaussian Blur", fontsize=14, fontweight='bold')

axes[0].imshow(img_eq, cmap='gray')
axes[0].set_title("Before Gaussian Blur")
axes[0].axis('off')

axes[1].imshow(img_blur, cmap='gray')
axes[1].set_title("After Gaussian Blur")
axes[1].axis('off')

plt.tight_layout()
plt.show()

"""##  **Teknik 2 - Thresholding**"""

thresh_value = 50
ret, img_thresh = cv2.threshold(img_blur, thresh_value, 255, cv2.THRESH_BINARY_INV)

fig, axes = plt.subplots(1, 2, figsize=(8, 4))
fig.suptitle("Teknik 5 - Thresholding", fontsize=14, fontweight='bold')

axes[0].imshow(img_blur, cmap='gray')
axes[0].set_title("Before Thresholding")
axes[0].axis('off')

axes[1].imshow(img_thresh, cmap='gray')
axes[1].set_title(f"After Thresholding with thresholding value = {thresh_value})")
axes[1].axis('off')

plt.tight_layout()
plt.show()

"""## **Teknik 3 - Operasi Morfologi (Opening)**"""

kernel = np.ones((5,5), np.uint8)
img_morph = cv2.morphologyEx(img_thresh, cv2.MORPH_OPEN, kernel)

fig, axes = plt.subplots(1, 2, figsize=(8, 4))
fig.suptitle("Teknik 6 - Opening", fontsize=14, fontweight='bold')

axes[0].imshow(img_thresh, cmap='gray')
axes[0].set_title(f"before opening")
axes[0].axis('off')

axes[1].imshow(img_morph, cmap='gray')
axes[1].set_title("after opening")
axes[1].axis('off')

plt.tight_layout()
plt.show()

"""# 4. Analisis & Fitur Ekstraksi"""

# Analisis & Fitur Ekstraksi
# Ekstraksi fitur yang dipilih
# Visualisasi dan interpretasi fitur
# Perbandingan fitur (jika ada)

"""## Ekstrasi Fitur"""

def extract_shape_features(binary_image):
    """
    Ekstraksi fitur bentuk menggunakan:
    - Contour Detection
    - Feature Extraction (Area & Circularity)
    """

    contours, _ = cv2.findContours(
        binary_image,
        cv2.RETR_EXTERNAL,
        cv2.CHAIN_APPROX_SIMPLE
    )

    features = []

    for cnt in contours:
        area = cv2.contourArea(cnt)
        perimeter = cv2.arcLength(cnt, True)

        circularity = 0
        if perimeter != 0:
            circularity = 4 * np.pi * area / (perimeter ** 2)

        features.append({
            "Area": area,
            "Circularity": circularity
        })

    return features

# Visualisasi kontur pada citra asli
visual_img = original_image.copy()
cv2.drawContours(visual_img, contours, -1, (255, 0, 0), 2)

plt.figure(figsize=(6,6))
plt.imshow(cv2.cvtColor(visual_img, cv2.COLOR_BGR2RGB))
plt.title("Visualisasi Kontur Mata Kayu")
plt.axis("off")
plt.show()

areas = [f["Area"] for f in features]
circularities = [f["Circularity"] for f in features]

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
plt.hist(areas, bins=30)
plt.title("Distribusi Area Mata Kayu")
plt.xlabel("Area")
plt.ylabel("Frekuensi")

plt.subplot(1,2,2)
plt.hist(circularities, bins=30)
plt.title("Distribusi Circularity Mata Kayu")
plt.xlabel("Circularity")
plt.ylabel("Frekuensi")

plt.tight_layout()
plt.show()

"""## Interpretasi dan Perbandingan Fitur"""

Nilai Area yang besar menunjukkan mata kayu yang signifikan,
sedangkan Circularity mendekati 1 menunjukkan bentuk bulat.

Objek dengan area besar dan circularity tinggi memiliki dampak
kualitas yang lebih signifikan dibandingkan objek kecil.

"""# 5. Analisis Komparatif"""

# Analisis Komparatif
# Rangkuman hasil semua teknik yang digunakan
# Rekomendasi teknik terbaik untuk dataset



"""# 6. Kesimpulan"""



